### ISSUE TITLE
Mixed responsibilities for Slider

### ISSUE THREAD

**Issue by cosminnicula** [telerik/kendo-react-inputs#16]
When you look at the `Slider`’s event handlers `onTickClick`, `onTrackClick`, `onKeyDown`, `onIncrease`, `onDecrease` you can see that their implementation are doing two things in general:
  1. calculates the new value of the `Slider`
  2. notifies outside the new value so that the `Slider` and all its inner components will get a chance to react when it receives it back as a new prop

IMO there’s a bit of a problem here, because the `Slider` knows to do more than it should.
A better design would be to have the logic mentioned at 1. placed inside its corresponding component. E.g.: move the first two lines from `onTrackClick` to `SliderTrack` in the `onClick` event handler; move the first three lines from `onTickClick` to `SliderTicks` in the `onClick` event handler, since `SliderTicks` is the only one that really knows how to build the `SliderTick` collection; move all the code inside `onKeyDown`, except `this.props.onChange({ value })`, together with `keyBinding` to `SliderTrack` in the `onKeyDown` event handler.  For `onIncrease` and `onDecrease`, the `SliderButton` would need an additional flag to know whether to calculate the increased or decreased value.

By doing this, you also solve the problem of having the `Slider` become too bloated and additionally you’ll have the `SliderTrack`, `SliderTicks` and `SliderButton` components more autonomous.

**Comment by KirilNN** [comment]
Hi @cosminnicula,

Thanks for your input.

What we tried to do is keep the child components as `dummy` as possible, and this is why we have all the event handlers in the parent component, and have the `SliderTrack` or `SliderTicks` just do simple rendering.

**Comment by cosminnicula** [comment]
Thanks for the feedback. Just wondering if this pattern has advantages that can overcome the problems of having the parent component grow in complexity as it holds more children logic.

**Comment by KirilNN** [comment]
The idea for a `dummy` component is to have no additional dependencies (like the calculation logic) and to receive only props and provide data/callbacks.

**Comment by cosminnicula** [comment]
Then all the additional dependencies will live inside the parent - which will make it more complex and hard to test in the future. The alternative would be to have each child designed with its own set of responsibilities (e.g. calculation logic) and balance the situation.
